config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#dashboard', as: 'dashboard'

  post '/tasks', to: 'tasks#create'
  post '/tasks/:id/complete', to: 'tasks#complete', as: 'complete_task'

  get '/status', to: 'status#status'

  get '/all_days', to: 'dashboard#all_days', as: 'all_days'

  get '/all_days/:day', to: 'dashboard#single_day', as: 'single_day'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def dashboard
    tasks = Task.where('created_at >= ?', Time.zone.now.beginning_of_day)
    @time_now = Time.now.localtime.strftime('%d-%m-%Y')

    show_day(tasks)
  end

  def all_days
    date_range = 1.year.ago.to_date...Date.tomorrow.to_date

    @days = Task.where(created_at: date_range).map do |task|
      task.created_at.beginning_of_day
    end.uniq
  end

  def single_day
    day = Date.strptime(params[:day],'%d-%m-%Y')
    next_day = day + 1.day
    date_range = day...next_day

    tasks = Task.where(created_at: date_range)
    @time_now = day.strftime('%d-%m-%Y')

    show_day(tasks)

    render :template => 'dashboard/dashboard'
  end

  private

  def show_day(tasks)
    @tasks_programming = tasks.where(tag: 'Programming')
    @tasks_reading = tasks.where(tag: 'Reading')
    @tasks_sport = tasks.where(tag: 'Sport')
    @tasks_languages = tasks.where(tag: 'Languages')
    @tasks_university = tasks.where(tag: 'University')
    @tasks_daily_routine = tasks.where(tag: 'Daily Routine')

    @programming_percentage = percentage(@tasks_programming)
    @reading_percentage = percentage(@tasks_reading)
    @sport_percentage = percentage(@tasks_sport)
    @languages_percentage = percentage(@tasks_languages)
    @university_percentage = percentage(@tasks_university)
    @daily_routine_percentage = percentage(@tasks_daily_routine)
  end

  def percentage(tasks)
    return 0 if tasks.count == 0
    completed_tasks = tasks.where(completed: true).count
    ((completed_tasks.to_f / tasks.count) * 100).to_i
  end
end

app/controllers/status_controller.rb
class StatusController < ApplicationController
  def status
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
    title_parts = params[:title].split('#')
    title = title_parts[0].strip
    tag = title_parts[1]
    Task.create(title: title, tag: tag)
    redirect_to(dashboard_url)
  end

  def complete
    task = Task.find(params[:id])
    task.completed = true
    task.save

    redirect_to(dashboard_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/status_helper.rb
module StatusHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/dashboard/_task_category.html.erb
<ul class="<%= category %> categories">

  <div class="w3-light-grey w3-round progress-bar">
    <div class="w3-container w3-round w3-green progress-bar-indicator" style="width: <%= percentage %>%">
      <%= percentage %>%
    </div>
  </div>

  <% if tasks.empty? %>
    <div class="no-tasks">Still no tasks for today</div>
  <% end %>

  <% tasks.each do |task| %>
      <li class="<%= 'completed' if task.completed %>">
                <span class="checkbox">
                  <% if task.completed %>
                    &#10003;
                  <% end %>
                </span>
        <%= link_to task.title, complete_task_url(task.id), method: :post %>
      </li>
  <% end %>
</ul>

app/views/dashboard/all_days.html.erb
<div class="navigation">
  <div id="logo">
    <h1>ToDoDaily</h1>
  </div>

  <div id="all_days">
    <a href="<%= dashboard_url %>">Back to TODOs</a>
  </div>
</div>

<div class="header">
  <h1>Completed TODOs by days</h1>
</div>

<% @days.each do |day| %>
    <div class="previous-day">
      <a href="<%= single_day_url(day.strftime('%d-%m-%Y')) %>"><%= day.strftime('%d-%m-%Y') %></a>
    </div>
<% end %>

app/views/dashboard/dashboard.html.erb
<div>
  <div class="navigation">
    <div id="logo">
      <h1>ToDoDaily</h1>
    </div>

    <form id="add_task_form" action="/tasks" method="post">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <input type="text" name="title" placeholder="Add a new task with #tag..." onkeypress="onAddFormPress"/>
    </form>

    <div id="all_days">
      <a href="<%= all_days_url %>">All Days</a>
    </div>
  </div>

  <div class="header">
    <h2>What have I already done?</h2>
    <div class="current-date">
      <h3><b><%= @time_now %></b></h3>
    </div>
  </div>

  <div class="tasks-container">
    <div class="tasks">
      <div class="programming-container">
        <div class="programming-percentage percentage">
          <h2>Programming</h2>
          <span>
              <b>
                <%= @programming_percentage %>% / 100%
              </b>
          </span>
        </div>
        <%= render 'task_category', category: 'programming',
                   tasks: @tasks_programming,
                   percentage: @programming_percentage %>
      </div>

      <div class="university-container">
        <div class="university-percentage percentage">
          <h2>University</h2>
          <span>
            <b>
              <%= @university_percentage %>% / 100%
            </b>
          </span>
        </div>
        <%= render 'task_category', category: 'university',
                   tasks: @tasks_university,
                   percentage: @university_percentage %>
      </div>

      <div class="sport-container">
        <div class="sport-percentage percentage">
          <h2>Sport</h2>
          <span>
            <b>
              <%= @sport_percentage %>% / 100%
            </b>
          </span>
        </div>
        <%= render 'task_category', category: 'sport',
                   tasks: @tasks_sport,
                   percentage: @sport_percentage %>
      </div>

      <div class="languages-container">
        <div class="languages-percentage percentage">
          <h2>Languages</h2>
          <span>
            <b>
              <%= @languages_percentage %>% / 100%
            </b>
          </span>
        </div>
        <%= render 'task_category', category: 'languages',
                   tasks: @tasks_languages,
                   percentage: @languages_percentage %>
      </div>

      <div class="reading-container">
        <div class="reading-percentage percentage">
          <h2>Reading</h2>
          <span>
            <b>
              <%= @reading_percentage %>% / 100%
            </b>
          </span>
        </div>
        <%= render 'task_category', category: 'reading',
                   tasks: @tasks_reading,
                   percentage: @reading_percentage %>
      </div>

      <div class="daily-routine-container">
        <div class="daily-routine-percentage percentage">
          <h2>Daily Routine</h2>
          <span>
            <b>
              <%= @daily_routine_percentage %>% / 100%
            </b>
          </span>
        </div>
        <%= render 'task_category', category: 'daily-routine',
                   tasks: @tasks_daily_routine,
                   percentage: @daily_routine_percentage %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoDaily</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/status/status.html.erb
<h1>Status</h1>
<p>OK</p>